[phases.setup]
nixPkgs = ["nodePackages.pnpm", "nodejs-20_x"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter web build"]

[start]
cmd = "pnpm --filter web start"
