[build]
builder = "nixpacks"
installCommand = "pnpm install --frozen-lockfile"
# هنستخدم الـ build العادي ونعطل الـ linting مؤقتاً عشان نضمن النجاح
buildCommand = "pnpm db:generate && NEXT_PRIVATE_SKIP_SCRC=true pnpm --filter web build"

[deploy]
startCommand = "cd apps/web && pnpm start"
restartPolicyType = "ON_FAILURE"
