[build]
builder = "nixpacks"
installCommand = "pnpm install --no-frozen-lockfile"
buildCommand = "npx turbo run build"

[deploy]
startCommand = "pnpm --filter web start"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
