[build]
builder = "nixpacks"
installCommand = "pnpm install --frozen-lockfile"
buildCommand = "npx turbo run build --filter=web..."

[deploy]
startCommand = "pnpm --filter web start"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
